service: api
runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 1000

handlers:
  - url: /.*
    script: auto

runtime_config:
  runtime_version: "16"

entrypoint: node index.js
