service: api
runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100

handlers:
  - url: /.*
    script: auto
    http_headers:
      Access-Control-Allow-Origin: https://cis3111-2023-assignment-1.ew.r.appspot.com

runtime_config:
  runtime_version: "16"

entrypoint: node index.js
