service: api
runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 5
  max_num_instances: 15

handlers:
  - url: /.*
    script: auto

runtime_config:
  runtime_version: "16"

entrypoint: node index.js
